repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-ast
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: forbid-new-submodules
  - id: requirements-txt-fixer
  - id: flake8
  - id: debug-statements
  - id: detect-private-key
  - id: mixed-line-ending
    args:
    - --fix=lf
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.21
  hooks:
  - id: isort
